services:

  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - UID=1000
        - GID=1000
    volumes:
      - .:/home/user/dev
    working_dir: /home/user/dev
    entrypoint: /bin/bash

  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - UID=1000
        - GID=1000
    volumes:
      - .:/home/user/prod
    working_dir: /home/user/prod
